export const ACCOUNT_FETCH_REQESTED = 'ACCOUNT_FETCH_REQESTED';
export const ACCOUNT_FETCH_SUCCESSED = 'ACCOUNT_FETCH_SUCCESSED';
export const ACCOUNT_FETCH_FAILED = 'ACCOUNT_FETCH_FAILED';

export const ACCOUNT_SIGN_IN_REQUESTED = 'ACCOUNT_SIGN_IN_REQUESTED';
export const ACCOUNT_SIGN_IN_SUCCESSED = 'ACCOUNT_SIGN_IN_SUCCESSED';
export const ACCOUNT_SIGN_IN_FAILED = 'ACCOUNT_SIGN_IN_FAILED';

export const ACCOUNT_LOGOUT_REQESTED = 'ACCOUNT_LOGOUT_REQESTED';
export const ACCOUNT_LOGOUT_SUCCESSED = 'ACCOUNT_LOGOUT_SUCCESSED';
export const ACCOUNT_LOGOUT_FAILED = 'ACCOUNT_LOGOUT_FAILED';
