export const PLAYGROUNDS_FETCH_REQUESTED = 'PLAYGROUNDS_FETCH_REQUESTED';
export const PLAYGROUNDS_FETCH_SUCCESSED = 'PLAYGROUNDS_FETCH_SUCCESSED';
export const PLAYGROUNDS_FETCH_FAILED = 'PLAYGROUNDS_FETCH_FAILED';
